# Generated by Django 4.1.1 on 2022-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('state', models.CharField(choices=[('NEW', 'New'), ('EXISTS', 'Exists')], default='NEW', max_length=200, verbose_name='Status')),
                ('due_date', models.DateTimeField(max_length=300, verbose_name='Due date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
    ]
