# Generated by Django 4.1.1 on 2022-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_deleted_at_task_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('EXISTS', 'Exists')], default='NEW', max_length=100, verbose_name='State'),
        ),
    ]
